version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::475926679788:role/CodeStarWorker-mojito-CodeBuild
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/java:openjdk-8
  Timeout: 10

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - webapp/target/mojito-webapp*.jar
  discard-paths: no