version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BazaDate9
      MYSQL_DATABASE: mojito
      MYSQL_USER: mojito
      MYSQL_PASSWORD: BazaDate7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    depends_on:
      - db
    ports:
      - "8888:8080"
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
      "flyway.enabled": "true",
      "spring.jpa.database" : "MYSQL",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "none",
      "spring.datasource.url" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
      "spring.datasource.username" : "mojito",
      "spring.datasource.password" : "BazaDate7",
      "spring.datasource.driverClassName" : "com.mysql.jdbc.Driver",
      "spring.datasource.validation-query" : "SELECT 1"
      }'
volumes:
  mysql_data:
